workflows:
  ios-workflow:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get
      - name: Build IPA without signing
        script: flutter build ios --release --no-codesign
      - name: Create IPA
        script: |
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r app.ipa Payload
    artifacts:
      - app.ipa
    publishing:
      email:
        recipients:
          - "serrdar.sd@gmail.com"